# Generated by Django 4.2.11 on 2024-04-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=30),
        ),
    ]
