# Generated by Django 4.2.11 on 2024-05-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('GBP', 'Pound Sterling'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='GBP', max_length=3),
        ),
    ]
