# Generated by Django 4.2.11 on 2024-05-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_user_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=10, default=1000.0, max_digits=30),
        ),
    ]
