# Generated by Django 4.2.11 on 2024-03-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
