# Generated by Django 4.2.11 on 2024-03-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_transaction_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_convert',
            field=models.BooleanField(default=False),
        ),
    ]
