# Generated by Django 4.2.11 on 2024-04-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_transaction_is_convert'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
