# Generated by Django 4.2.11 on 2024-04-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_transaction_converted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency_sign',
            field=models.CharField(choices=[('GBP', 'Pound Sterling'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='USD', max_length=3),
        ),
    ]
