# Generated by Django 4.2.11 on 2024-05-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_transaction_currency_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='currency_sign',
            new_name='receiver_currency_sign',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_currency_sign',
            field=models.CharField(choices=[('GBP', 'Pound Sterling'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='USD', max_length=3),
        ),
    ]
